export const API_URL=import.meta.env.VITE_DEV_API_URL
export const CLOUDINARY_URL=import.meta.env.VITE_CLOUDINARY_URL
export const BUYER_CLOUDINARY_URL=import.meta.env.VITE_BUYER_CLOUDINARY_URL
export const DRIVER_CLOUDINARY_URL=import.meta.env.VITE_DRIVER_CLOUDINARY_URL